modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/kvnmtz/mercantile/issues"
license = "ARR"

[[mods]]
    modId = "$mod_id"
    version = "$version"
    displayName = "Mercantile"
    authors = "3xpl01t"
    description = '''
    Adds a simple currency system with optional Create 6+ integration.
    '''
    logoFile = "icon.png"

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[$minecraft_version]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "architectury"
    mandatory = true
    versionRange = "[$architectury_api_version,)"
    ordering = "AFTER"
    side = "BOTH"
    [dependencies.${mod_id}.mc-publish]
        ignore = false
        modrinth="architectury-api"
        curseforge="architectury-api"

[[dependencies.${mod_id}]]
    modId = "create"
    mandatory = false
    versionRange = "[$create_version_short,)"
    ordering = "NONE"
    side = "BOTH"